name: deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - feature/**
      - bugfix/**
      - hotfix/**
      - refact**/**
      - releases
      - dependabot/

env:
  BLIP_APP_KEY: ${{ secrets.REACT_APP_BLIP_KEY }}

jobs:
  build:
    name: Build the Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Build web-app
        env:
          CI: true
          REACT_APP_BLIP_KEY: ${{ secrets.REACT_APP_BLIP_KEY }}
        run: |
          npm install -g npm
          npm install -g yarn
          yarn preci
          yarn ci
          yarn build
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

  notify-prod:
    name: Discord Notify Production CI
    runs-on: ubuntu-latest
    needs:
      - build
    if: ${{ always() && github.event_name != 'pull_request' }}

    steps:
      - name: Notify
        uses: nobrayner/discord-webhook@v1
        with:
          title: '${{ github.ref_name }} - ${{ github.workflow }}: {{STATUS}}'
          github-token: ${{ secrets.github_token }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
          description: '**Production deploy**'
          include-details: 'true'

  notify-pr:
    name: Discord Notify Pull Request CI
    runs-on: ubuntu-latest
    needs:
      - build
    if: ${{ always() && github.event_name == 'pull_request' }}

    steps:
      - name: Notify
        uses: nobrayner/discord-webhook@v1
        with:
          title: '${{ github.head_ref }} - ${{ github.workflow }}: {{STATUS}}'
          github-token: ${{ secrets.github_token }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
          description: ${{ github.event.pull_request.title }}
          include-details: 'true'
